### ISSUE TITLE
Include RDA Definition and Scope?

### ISSUE THREAD

**Issue by ladylazarus3** [ladylazarus3/Test2#1]
Should we introduce RDA’s definition and scope with a standard label, e.g. “RDA Definition and Scope”?

**Comment by ladylazarus3** [comment]
i added a Definition and scope to the beginning of the Title Proper Entity
https://ladylazarus3.github.io/Test2/docs/title/Title-proper/

**Comment by rarebkcat** [comment]
> i added a Definition and scope to the beginning of the Title Proper Entity
> https://ladylazarus3.github.io/Test2/docs/title/Title-proper/

I do think we'll have to be careful, as one of the things that pushed us to policy statements the first time was RDA claiming copyright over the words and wanting people not to reuse the text, whereas (as I understand it) AACR2 had a much more open-source/ remix ethos.
